version: '3'
services:

  t2isp-mysql:
    container_name: t2isp-mysql
    image: 'mysql:8.0'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: '@npm@t2web#123'
      MYSQL_ROOT_PASSWORD: '@mysql@t2web#123'
    volumes:
      - /opt/docker/data/mysql:/var/lib/mysql
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.2


  t2isp-zbxserver:
    container_name: t2isp-zbxserver
    image: 'zabbix/zabbix-server-mysql:ubuntu-6.0-latest'
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "t2isp-mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbixT2webAdmin"
      MYSQL_ROOT_PASSWORD: "@mysql@t2web#123"
      ZBX_STARTPOLLERS: 100
      ZBX_STARTPINGERS: 110
      ZBX_STARTPOLLERSUNREACHABLE: 20
      ZBX_CACHESIZE: 2G
      ZBX_VALUECACHESIZE: 1G
      ZBX_TRENDCACHESIZE: 512M
      ZBX_HISTORYCACHESIZE: 256M
      ZBX_HISTORYINDEXCACHESIZE: 128M
      ZBX_VMWARECACHESIZE: 128M
      ZBX_TIMEOUT: 30
      ZBX_MAXHOUSEKEEPERDELETE: 30000
      ZBX_SERVER_NAME: "ZBX-T2_ISP"
      ZBX_TRAPPERIMEOUT: 300
      ZBX_ENABLE_SNMP_TRAPS: true
    depends_on:
      - t2isp-mysql
    volumes:
      - /opt/docker/data/zabbix/server/alertscripts:/usr/lib/zabbix/alertscripts
      - /opt/docker/data/zabbix/server/externalscripts:/usr/lib/zabbix/externalscripts
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.3


  t2isp-zbxfront:
    container_name: t2isp-zbxfront
    image: 'zabbix/zabbix-web-apache-mysql:ubuntu-6.0-latest'
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: "t2isp-mysql"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbixT2webAdmin"
      MYSQL_ROOT_PASSWORD: "@mysql@t2web#123"
      PHP_TZ: "America/Sao_Paulo"
      ZBX_UPLOADMAXFILESIZE: 50M
      ZBX_SERVER_NAME: "ZBX-T2WEB_ISP"
      VIRTUAL_HOST: "zbxisp.t2web.com.br"
      ZBX_SERVER_HOST: "10.20.30.3"
    depends_on:
      - t2isp-mysql
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.4


  t2isp-grafana:
    container_name: t2isp-grafana
    image: 'grafana/grafana:10.0.0-ubuntu'
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: "alexanderzobnin-zabbix-app,grafana-singlestat-panel,yesoreyeram-boomtheme-panel,grafana-clock-panel,grafana-piechart-panel"
    user: '0'
    volumes:
      - /opt/docker/data/grafana:/var/lib/grafana
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.5


  t2isp-dns:
    container_name: t2isp-bind9
    image: 'labbsr0x/dns-bind9'
    restart: unless-stopped
    expose:
      - '53'
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
      -  /opt/docker/data/bind9/data:/data
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.6


  t2isp-npm:
    container_name: t2isp-npm
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DB_MYSQL_HOST: 10.20.30.2
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "@npm@t2web#123"
      DB_MYSQL_NAME: "npm"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /opt/docker/data/nginxproxymanager/data:/data
      - /opt/docker/data/nginxproxymanager/letsencrypt:/etc/letsencrypt
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.7

  portainer:
    image: portainer/portainer-ce:latest
    container_name: t2isp-portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/data/portainer/data:/data
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.8

  t2isp-ntp:
    image: cturra/ntp:latest
    container_name: t2isp-ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
      - TZ=America/Sao_Paulo
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.9

  t2isp-tacacs:
    image: lfkeitel/tacacs_plus:latest
    container_name: t2isp-tacacs
    restart: always
    ports:
      - 49:4949
    volumes:
      - /opt/docker/data/tacacs/:/etc/tac_plus/
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.10

  t2isp-krill:
    image: nlnetlabs/krill
    container_name: t2isp-krill
    environment:
      - KRILL_LOG_LEVEL=debug
      - KRILL_FQDN=rpki-jnet-rpki.t2web.com.br
      - KRILL_AUTH_TOKEN=rpki@T2#8183
      - TZ=America/Sao_Paulo
    volumes:
     - /opt/docker/data/krill:/var/krill/data/
    restart: always
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.11

  t2isp-routinator:
    image: nlnetlabs/routinator
    container_name: t2isp-routinator
    restart: unless-stopped
    networks:
      t2web-isp:
        ipv4_address: 10.20.30.12

networks:
  t2web-isp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
          gateway: 10.20.30.1
